name: Add General Technical Review Comment
on: 
  issues:
    types:
      - labeled
jobs:
  add-comment:
    if: github.event.label.name == 'gtr'
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: Add General Technical Review comment
        run: gh issue comment "$NUMBER" --body "$BODY"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_REPO: ${{ github.repository }}
          NUMBER: ${{ github.event.issue.number }}
          BODY: >
            This is a comment discussing what to expect with the General Technical Review questions.
            :sparkles: Thank you! :sparkles:
